import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'
import MailingList from '../components/MailingList'
import { ResponsiveNavBar } from '../components/ResponsiveNavbar'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='bg-slate-50'>
        <ResponsiveNavBar />
        <Hero />
      </div>
      <MailingList />
    </>
  )
}
